spring:
  application:
    name: crossfit-periodization
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5432/periodization
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8080

anthropic:
  api:
    key: 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
    url: https://api.anthropic.com/v1/messages
    model: claude-3-7-sonnet-20250219

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

file:
  storage:
    path: ${FILE_STORAGE_PATH:./files}
