spring:
  application:
    name: periodization
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000  # 30 segundos
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VHOST}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

anthropic:
  api:
    key: ${ANTHROPIC_API_KEY}
    url: https://api.anthropic.com/v1/messages
    model: claude-3-7-sonnet-20250219

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

file:
  storage:
    path: ${FILE_STORAGE_PATH:./files}

app:
  logo:
    url: ${APP_LOGO_URL}
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000 # 24 horas em milissegundos
    refresh-expiration: 604800000 # // 7 dias em milisegundos
  oauth2:
    redirectUri: ${OAUTH2_REDIRECT_URI}
  frontend-url: ${FRONT_URL}
  backend-url: ${BACK_URL}

mercado-pago:
  access-token: ${MERCADO_PAGO_TOKEN}

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG